services:
  db:
    image: pgvector/pgvector:pg16
    container_name: benchmark_db
    restart: always
    environment:
      POSTGRES_USER: benchmark_user
      POSTGRES_PASSWORD: benchmark_password
      POSTGRES_DB: benchmark_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: benchmark_redis
    ports:
      - "6379:6379"

  pgadmin:
    image: dpage/pgadmin4
    container_name: benchmark_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@benchmark.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
